version: '3.9'
services:
  app:
    container_name: app
    image: taskmanagment/app:1.0.0
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - database


  database:
    container_name: database
    image: postgres:13.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}