spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: spring123

application:
  security:
    jwt:
      secret-key: 472D4B6150645367566B597033733676397924423F4528482B4D625165546857
      access_token:
        expiration: 60000
      refresh_token:
        expiration: 604800000


